library(arules)
library(arulesViz)
source("http://news.mrdwab.com/install_github.R")
install_github("mrdwab/SOfun")
library(SOfun)
library(tidyr)
library(data.table)
library(reshape2)
#data.forests = read.table(file="forests.txt",sep = "\n",fill = TRUE,col.names = "Species")
#nodata <- setNames(replicate(104,numeric(0), simplify = F), letters[1:104])
#data.forests=transform(data.forests,reshape::colsplit(data.forests$Species,split="\t",names = nodata))
#m2<-cbind(1:206)
#colnames(m2)<-c(1:206)
#colnames<-paste("Species",colnames(m2),sep ="_")
#all_lm<- matrix(nrow = 246,ncol = 206)
#as.data.frame(all_lm,col.names=colnames)

trans_4 = read.transactions(file="forests.txt",format = "basket")
trans_4= as(trans_4,"data.frame")
param_4 <- list(support=0.6,confidence=0.3,minlen=2,target="rules")
Question_4 = arules::apriori(trans_4,param_4)
split.into.cols<- transform(trans_4,reshape::colsplit(trans_4$items,split=","))
superset.Question_4 = Question_4[is.maximal(Question_4)]
firstrow<- trans_4[1,]
#rownames<-t(as.data.frame(strsplit(firstrow, '\t')))

#nodata <- as.data.frame(setNames(replicate(246,numeric(0), simplify = F), letters[1:246]))
#firstrow<-unlist((data.forests[1,]))
#setNames(setDF(lapply(firstrow, function(x) eval(call(x)))), colnames)
#pawned<-tidyr::separate(firstrow,into = c(make.names(numeric(0),unique = TRUE)) , sep = "\t")
source(file = "cSplit.R")
cSplit(as.data.table(data.forests1),"text","\t")
apply(data.forests,1,unlist)
data.forests.cols=rbind(data.forests[!sapply(data.forests, is.list)],
      (t(apply(data.forests[sapply(data.forests, is.list)], 1, unlist))))
apriori.rules = arules::apriori(data.forests,parameter = list(minlen=2))
